version: "3"
networks:
  develop:
    external: true

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    networks:
      - develop
    environment:
      - POSTGRES_PASSWORD=Password1
    volumes:
      - ~/dev/docker/volumes/postgres:/var/lib/postgresql/data:rw
#  babelfish:
#    image: coolincy/babelfish:14
#    container_name: babelfish
#    hostname: babelfish
#    ports:
#      - "5432:5432"
#      - "1433:1433"
#    networks:
#      - develop
#    environment:
#      - POSTGRES_PASSWORD=Password1
#    volumes:
#      - ~/dev/docker/volumes/postgres:/var/lib/postgresql/data:rw
#    command: -u sa -p Password1 -d postgres -m single-db #multi-db
    