version: "3"
networks:
  develop:
    external: true

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    networks:
      - develop
    environment:
      - POSTGRES_PASSWORD=Password1
    volumes:
      - ~/docker/volumes/postgres:/var/lib/postgresql/data:rw
