FROM mcr.microsoft.com/dotnet/sdk:8.0

ARG username
ARG password

RUN apt update && apt install openssh-server sudo -y

RUN useradd -rm -d /home/$username -s /bin/bash -g root -G sudo -u 1000 $username

RUN  echo "$username:$password" | chpasswd

RUN service ssh start

EXPOSE 22

CMD ["/usr/sbin/sshd","-D"]
